version: '3'

services:
  flask:
    build: ./app
    command: gunicorn -w 4 -b 0.0.0.0:5000 main:app --reload
    container_name: app

    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONBUFFERED=1

    ports:
      - "5000:5000"
    volumes:
      - ./app:/flask-app

  tgbot:
    build: ./tg-bot
    command: python bot.py
    container_name: tg-bot
